version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:17.2

    working_directory: ~/film-flix

    steps:
      - checkout

      - run:
          name: Install pnpm globaly
          command: sudo npm install -g pnpm

      - run:
          name: Install dependencies
          command: |
            cd film-flix
            pnpm install

      - run:
          command: |
            cd film-flix
            pnpm test

      - run:
          name: Build
          command: |
            cd film-flix
            pnpm run build

    orbs:
      slack: circleci/slack@4.9.3

    jobs:
      notify:
        docker:
          - image: 'cimg/base:stable'
        steps:
          - slack/notify:
              custom: |
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": ":rocket: *Custom Notification* :rocket:"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Status:*\nSuccess"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Branch:*\ndev"
                        }
                      ]
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "More details about the notification..."
                      }
                    }
                  ]
                }
              event: always


#  deploy:
#    docker:
#      - image: circleci/node:14
#
#    working_directory: ~/film-flix
#
#    steps:
#      - checkout
#
#      # Add deployment steps here, for example, deploying to a hosting service.

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
  send_notification:
    jobs:
        - notify
      # Uncomment the following line and add your deploy job if needed.
      # - deploy