version: 2.1

orbs:
  slack: circleci/slack@4.9.3
  codecov: codecov/codecov@3.3.0

jobs:
  build:
    docker:
      - image: circleci/node:17.2

    working_directory: ~/film-flix

    steps:
      - checkout

      - run:
          name: Install pnpm globally
          command: sudo npm install -g pnpm

      - run:
          name: Install dependencies
          command: |
            cd film-flix
            pnpm install

      - run:
          name: Run tests
          command: |
            cd film-flix
            pnpm test

      - run:
          name: Build
          command: |
            cd film-flix
            pnpm run build

      - codecov/upload:
          file: ~/film-flix/coverage/lcov.info
          flags: codecov/project
          name: codecov-coverage-upload
          token: $CODECOV_TOKEN

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":rocket: *Custom Notification* :rocket:"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\nSuccess"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\ndev"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Details of the notification..."
                  }
                }
              ]
            }
          event: always
    environment:
      SLACK_ACCESS_TOKEN: $SLACK_ACCESS_TOKEN

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
      - notify


