name: Test Coveralls

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 21.x]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: cd ./film-flix && pnpm install

      - name: pnpm install, make test-coverage
        run: cd ./film-flix && pnpm run coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./film-flix/coverage/lcov.info